language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - ls
  - git status
  - ls ~
  - echo $HOME
  - env

script:
  - echo hello
  - env
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=ON
  - make -j 4
  - make install
  - # source ../dist/bin/easycl_activate.sh
  - otools -L ../dist/bin/easycl_unittests
  - otools -l ../dist/bin/easycl_unittests | grep RPATH -A2
  - otools -L ../dist/lib/libEasyCL.so
  - otools -l ../dist/lib/libEasyCL.so | grep RPATH -A2
  - ../dist/bin/gpuinfo
  - ../dist/bin/easycl_unittests tests=-SLOW*:testlocal*:testnewinstantiations.createForFirstGpu:testnewinstantiations.createForIndexedGpu

notifications:
  email:
    on_success: never
    on_failure: never
